// ignore_for_file: avoid_print
void main() {
  print('''
======================================================
Please run the following SQL command in your Supabase 
SQL Editor to create the inward_posts table:
======================================================

CREATE TABLE public.inward_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name text NOT NULL,
  recipient_name text NOT NULL,
  received_by text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'pendingConfirmation',
  received_date timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Optional: Enable Row Level Security (RLS) if needed
-- ALTER TABLE public.inward_posts ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable all access for inward_posts" ON public.inward_posts FOR ALL USING (true) WITH CHECK (true);

======================================================
''');
}
